<a href="https://colab.research.google.com/github/345bc/th-deep-learning/blob/main/BTTuan02_Datatleakage_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#Mô hình ANN

In [1]:
from google.colab import files
upload = files.upload()

Saving 23_HOMES.csv to 23_HOMES.csv

In [2]:
import pandas as pd

In [3]:
df =  pd.read_csv('23_HOMES.csv')

df.info()
print(df.head(20))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Selling_Price  40 non-null     int64
 1   List_Price     40 non-null     int64
 2   Area           40 non-null     int64
 3   Acres          40 non-null     float64
 4   Age            40 non-null     int64
 5   Taxes          40 non-null     int64
 6   Rooms          40 non-null     int64
 7   Bedrooms       40 non-null     int64
 8   Baths_full     40 non-null     int64
dtypes: float64(1), int64(8)
memory usage: 2.9 KB
    Selling_Price  List_Price  Area  Acres  Age  Taxes  Rooms  Bedrooms  \
0          400000      414000  2704   2.27   27   4920      9         3
1          370000      379000  2096   0.75   21   4113      8         4
2          382500      389900  2737   1.00   36   6072      9         4
3          300000      299900  1800   0.43   34   4024      8         4
4          305000      319900  1066   3.60   69   3562      6         3
5          320000      319900  1820   1.70   34   4672      7         3
6          321000      328900  2700   0.81   35   3645      8         3
7          445000      450000  2316   2.00   19   6256      9         4
8          377500      385000  2448   1.50   40   5469      9         4
9          460000      479000  3040   1.09   20   6740     10         4
10         265000      275000  1500   1.60   39   4046      6         2
11         299000      299000  1448   0.42   44   3481      7         3
12         385000      379000  2400   0.89   33   4411      9         4
13         430000      435000  2200   4.79    6   5714      8         4
14         214900      219900  1635   0.25   49   2560      5         3
15         475000      485000  2224  11.58   21   7885      7         3
16         280000      289000  1738   0.46   49   3011      8         3
17         457000      499900  3432   1.84   14   9809     11         4
18         210000      224900  1175   0.94   64   1367      7         3
19         272500      274900  1393   1.39   44   2317      6         3

    Baths_full
0            3
1            2
2            2
3            2
4            2
5            2
6            1
7            2
8            3
9            2
10           2
11           1
12           3
13           2
14           1
15           2
16           2
17           3
18           1
19           1

Ma trận tương quan

In [4]:
# Tính toán ma trận tương quan giữa tất cả các cột số
correlation_matrix = df[['Selling_Price', 'List_Price', 'Area', 'Acres', 'Age', 'Taxes', 'Rooms', 'Bedrooms', 'Baths_full']].corr()

# Hiển thị bảng tương quan
correlation_matrix

,Selling_Price,List_Price,Area,Acres,Age,Taxes,Rooms,Bedrooms,Baths_full
Selling_Price,1.000000,0.994900,0.801569,0.463429,-0.488228,0.832887,0.635046,0.551549,0.586037
List_Price,0.994900,1.000000,0.808390,0.457587,-0.492844,0.849244,0.654371,0.554956,0.580050
Area,0.801569,0.808390,1.000000,0.060500,-0.382098,0.822721,0.821298,0.610277,0.653148
Acres,0.463429,0.457587,0.060500,1.000000,-0.126363,0.314183,-0.124652,-0.077942,0.099913
Age,-0.488228,-0.492844,-0.382098,-0.126363,1.000000,-0.572243,-0.483822,-0.332976,-0.406182
Taxes,0.832887,0.849244,0.822721,0.314183,-0.572243,1.000000,0.700140,0.479176,0.647438
Rooms,0.635046,0.654371,0.821298,-0.124652,-0.483822,0.700140,1.000000,0.726356,0.639259
Bedrooms,0.551549,0.554956,0.610277,-0.077942,-0.332976,0.479176,0.726356,1.000000,0.485913
Baths_full,0.586037,0.580050,0.653148,0.099913,-0.406182,0.647438,0.639259,0.485913,1.000000

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline

In [35]:

X = df[['Area', 'Acres', 'Age', 'Bedrooms', 'Baths_full']]
y = df['Selling_Price']

Chia tập dữ liệu

In [36]:
X_train,X_test, y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [37]:
features=['Area', 'Acres', 'Age', 'Bedrooms', 'Baths_full']

In [38]:
preprocess = ColumnTransformer([
    ('num_scaler', MinMaxScaler(), features)
])

In [39]:
model = Pipeline([
    ('preprocess', preprocess),
    ('model', MLPRegressor(
        hidden_layer_sizes=(64, 32),
        activation='relu',
        solver='adam',
        max_iter=100000,
        random_state=42
    ))
])

In [40]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num_scaler', MinMaxScaler(),
                                                  ['Area', 'Acres', 'Age',
                                                   'Bedrooms',
                                                   'Baths_full'])])),
                ('model',
                 MLPRegressor(hidden_layer_sizes=(64, 32), max_iter=100000,
                              random_state=42))])

In [41]:
score = model.score(X_test, y_test)
print(score)

0.6606138254764164

In [42]:
predict = model.predict(X_test)
print(predict)
print(y_test.values)

[279943.15916898 275668.35417652 577207.52870479 421142.3660235
 273072.0722203  360650.79154001 310490.17542318 328393.3818845 ]
[272500 280000 475000 499000 305000 385000 300000 292000]

In [43]:
df_ket_qua = pd.DataFrame({
    'Giá Thực Tế (y_test)': y_test.values,
    'Giá Dự Đoán (predict)': predict,
    'Chênh Lệch (Sai số)': y_test.values - predict
})

df_ket_qua.head(10)

   Giá Thực Tế (y_test)  Giá Dự Đoán (predict)  Chênh Lệch (Sai số)
0                272500          279943.159169         -7443.159169
1                280000          275668.354177          4331.645823
2                475000          577207.528705       -102207.528705
3                499000          421142.366024         77857.633976
4                305000          273072.072220         31927.927780
5                385000          360650.791540         24349.208460
6                300000          310490.175423        -10490.175423
7                292000          328393.381884        -36393.381884